version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-kms-example"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1j9lkswgn14da"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "KeyAdmin=\"admin\" KeyUser=\"admin\""

